"""Initial migration with all models

Revision ID: 044a35c7bcd7
Revises: 
Create Date: 2025-11-19 11:58:06.598051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '044a35c7bcd7'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table('categories',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_categories_id'),
                    'categories', ['id'], unique=False)
    op.create_index(op.f('ix_categories_name'),
                    'categories', ['name'], unique=True)
    op.create_table('exercises',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('title', sa.String(length=200), nullable=False),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('difficulty', sa.Enum('BEGINNER', 'INTERMEDIATE',
                                                    'ADVANCED', name='difficultylevel'), nullable=False),
                    sa.Column('function_name', sa.String(
                        length=100), nullable=False),
                    sa.Column('created_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.Column('updated_at', sa.DateTime(timezone=True),
                              server_default=sa.text('now()'), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_exercises_difficulty'),
                    'exercises', ['difficulty'], unique=False)
    op.create_index(op.f('ix_exercises_id'), 'exercises', ['id'], unique=False)
    op.create_index(op.f('ix_exercises_title'),
                    'exercises', ['title'], unique=False)
    op.create_table('examples',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('exercise_id', sa.Integer(), nullable=False),
                    sa.Column('input', sa.Text(), nullable=False),
                    sa.Column('output', sa.Text(), nullable=False),
                    sa.Column('explanation', sa.Text(), nullable=True),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_examples_id'), 'examples', ['id'], unique=False)
    op.create_table('exercise_categories',
                    sa.Column('exercise_id', sa.Integer(), nullable=False),
                    sa.Column('category_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(
                        ['category_id'], ['categories.id'], ondelete='CASCADE'),
                    sa.ForeignKeyConstraint(
                        ['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('exercise_id', 'category_id')
                    )
    op.create_table('test_cases',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('exercise_id', sa.Integer(), nullable=False),
                    sa.Column('input_data', sa.JSON(), nullable=False),
                    sa.Column('expected_output', sa.JSON(), nullable=False),
                    sa.Column('is_public', sa.Boolean(), nullable=True),
                    sa.Column('description', sa.Text(), nullable=False),
                    sa.Column('order', sa.Integer(), nullable=True),
                    sa.ForeignKeyConstraint(
                        ['exercise_id'], ['exercises.id'], ondelete='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_test_cases_id'),
                    'test_cases', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_test_cases_id'), table_name='test_cases')
    op.drop_table('test_cases')
    op.drop_table('exercise_categories')
    op.drop_index(op.f('ix_examples_id'), table_name='examples')
    op.drop_table('examples')
    op.drop_index(op.f('ix_exercises_title'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_difficulty'), table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
